# Indentation -> at least 1 space (default: 4 spaces)
# Usage -> blocks of code: loops, functions, ...
# It's required in Python! -> raise IndentationError

# for loop:
for number in range(10):
    print(f"{number} -> Amir404!!") # -> ....

# function:
def print_message():
    print("Hi, Amir404!") # -> ....
print_message()

# Nested if-else statement:
age = 25
if age > 18:
    if age > 60:           # -> ....
        print("old!")      # -> ........
    else:                  # -> ....
        print("young!")    # -> ........
